Update patch set 2
Patch Set 2:

@Pankaj, I filed bug that Juniper CI can't check this, hence please use TF CI status.

Right now it has an error:


+ cp -pr LICENSE.trex /tmp/tmp.aAEidhXlgf/librdkafka-1.5.0-0contrail0.el7.x86_64/usr/share/doc/librdkafka1-1.5.0
cp: cannot stat â€˜LICENSE.trexâ€™: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.2SWJqN (%doc)
    Bad exit status from /var/tmp/rpm-tmp.2SWJqN (%doc)


http://nexus.jenkins.progmaticlab.com:8082/jenkins_logs/gerrit/80/60980/2/check_14385/build-centos/output-compile-centos.log

Patch-set: 2
Reviewer: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=0